project:
  artifactId: cdc-debezium-poc
  name: cdc-debezium-poc
  version: 1.0.0
  description: Change Data Capture(CDC) using embeded debezium engine to capture db changes and push to kafka topics in a micro service.


# Exposing all the actuator end points (Spring 2.0) #
management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  # Exposing the restart & shutdown endpoint
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true

# For Spring Actuator /info endpoint
info:
  artifact: ${project.artifactId}
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Spring
spring:
  application:
    name: cdc-debezium-poc

  #Postgres dB configuration.
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/datapipeline"
    username: test
    password: test9988
    driver-class-name: org.postgresql.Driver

  #JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: data_mbr_claims
      auto-offset-reset: earliest

# Kafka topic configuration where listening from topic
topic:
  name: mbr_claims

# use a HTTP port 8080
server:
  port: 8089


---
spring:
  profiles: stage

server:
  port: 8080


---
spring:
  profiles: prod

server:
  port: 8080



