project:
  artifactId: data-ingest-service
  name: data-ingest-service
  version: 1.0.0
  description: Data Ingest service is a micro service to ingest the data into the destination DB.


# Exposing all the actuator end points (Spring 2.0) #
management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  # Exposing the restart & shutdown endpoint
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true

# For Spring Actuator /info endpoint
info:
  artifact: ${project.artifactId}
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Spring
spring:
  application:
    name: data-ingest-service

  #Postgres dB configuration.
  datasource:
    platform: mssqlserver
    url: "jdbc:sqlserver://localhost;databaseName=pocingest"
    username: sa
    password: adminTest@20
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: mssqlserver
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect



  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: data_orders
      auto-offset-reset: earliest

# Kafka topic configuration where listening from topic
topic:
  ordert: orders


# use a HTTP port 8080
server:
  port: 8086


---
spring:
  profiles: stage

server:
  port: 8080


---
spring:
  profiles: prod

server:
  port: 8080



